---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ $.Release.Namespace }}
  lables:
    app: repolytics
spec:
  selector:
    matchLabels:
      app: repolytics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:      
      serviceAccountName: default
      securityContext:
        fsGroup: {{ .Values.security.pod_fs_group }}
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pull_policy }}
          securityContext:
            capabilities:
                drop:
                - ALL
            readOnlyRootFilesystem: {{ .Values.security.read__only_root_filesystem }}
            runAsGroup: {{ .Values.security.run_as_group }}
            runAsNonRoot: {{ .Values.security.run_as_non_root }}
            runAsUser: {{ .Values.security.run_as_user }}
          env:
            {{ range $key, $value := .Values.environment_variables }}
            - name: {{ $value.name | quote }}
              value: {{ $value.value | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret_environment_variables }}