---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:      
      serviceAccountName: default
      securityContext:
        fsGroup: {{ .security.pod_fs_group }}
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .image.repo }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pull_policy }}
          securityContext:
            capabilities:
                drop:
                - ALL
            readOnlyRootFilesystem: {{ .security.read__only_root_filesystem }}
            runAsGroup: {{ .security.run_as_group }}
            runAsNonRoot: {{ .security.run_as_non_root }}
            runAsUser: {{ .security.run_as_user }}
          env:
            {{ range $key, $value := .environment_variables }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            envFrom:
              - secretRef:
                  name: {{ .secret_environment_variables }}